// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sales.API.Models;

#nullable disable

namespace Sales.API.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20260516130039_ContractCompliance")]
    partial class ContractCompliance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sales.API.Models.CommandItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CommandId")
                        .HasColumnType("integer")
                        .HasColumnName("command_id");

                    b.Property<int?>("OrderItemId")
                        .HasColumnType("integer")
                        .HasColumnName("order_item_id");

                    b.Property<int?>("StationId")
                        .HasColumnType("integer")
                        .HasColumnName("station_id");

                    b.HasKey("Id")
                        .HasName("command_item_pkey");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("StationId");

                    b.ToTable("command_item", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("customer_pkey");

                    b.ToTable("customer", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.GlobalTaxConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("numeric(7,4)")
                        .HasColumnName("tax_rate");

                    b.HasKey("Id")
                        .HasName("global_tax_config_pkey");

                    b.ToTable("global_tax_config", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.OrderCommand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int?>("WaiterId")
                        .HasColumnType("integer")
                        .HasColumnName("waiter_id");

                    b.HasKey("Id")
                        .HasName("order_command_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("WaiterId");

                    b.ToTable("order_command", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNote")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("additional_note");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("ProductCen")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("product_cen");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("product_name");

                    b.Property<double?>("Qty")
                        .HasColumnType("double precision")
                        .HasColumnName("qty");

                    b.Property<int>("ResendCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("resend_count");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("sent_at");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("order_item_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("order_item", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.OrderStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("order_status_pkey");

                    b.ToTable("order_status", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.OrderTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("integer")
                        .HasColumnName("customer_id");

                    b.Property<int>("DailyNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("daily_number");

                    b.Property<int?>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<decimal?>("TaxRateSnapshot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(7,4)")
                        .HasDefaultValue(0m)
                        .HasColumnName("tax_rate_snapshot");

                    b.HasKey("Id")
                        .HasName("order_ticket_pkey");

                    b.HasIndex("CustomerId");

                    b.HasIndex("StatusId");

                    b.ToTable("order_ticket", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("paid_at");

                    b.Property<int?>("PaymentTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("payment_type_id");

                    b.HasKey("Id")
                        .HasName("payment_pkey");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentTypeId");

                    b.ToTable("payment", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.PaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("payment_type_pkey");

                    b.ToTable("payment_type", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.HasKey("Id")
                        .HasName("station_pkey");

                    b.HasIndex("TypeId");

                    b.ToTable("station", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.StationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("station_type_pkey");

                    b.ToTable("station_type", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.Waiter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("waiter_pkey");

                    b.ToTable("waiter", "sales");
                });

            modelBuilder.Entity("Sales.API.Models.CommandItem", b =>
                {
                    b.HasOne("Sales.API.Models.OrderItem", "OrderItem")
                        .WithMany("CommandItems")
                        .HasForeignKey("OrderItemId")
                        .HasConstraintName("command_item_order_item_id_fkey");

                    b.HasOne("Sales.API.Models.Station", "Station")
                        .WithMany("CommandItems")
                        .HasForeignKey("StationId")
                        .HasConstraintName("command_item_station_id_fkey");

                    b.Navigation("OrderItem");

                    b.Navigation("Station");
                });

            modelBuilder.Entity("Sales.API.Models.OrderCommand", b =>
                {
                    b.HasOne("Sales.API.Models.OrderTicket", "Order")
                        .WithMany("OrderCommands")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("order_command_order_id_fkey");

                    b.HasOne("Sales.API.Models.Waiter", "Waiter")
                        .WithMany("OrderCommands")
                        .HasForeignKey("WaiterId")
                        .HasConstraintName("order_command_waiter_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Waiter");
                });

            modelBuilder.Entity("Sales.API.Models.OrderItem", b =>
                {
                    b.HasOne("Sales.API.Models.OrderTicket", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("order_item_order_id_fkey");

                    b.HasOne("Sales.API.Models.OrderStatus", "Status")
                        .WithMany("OrderItems")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("order_item_status_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Sales.API.Models.OrderTicket", b =>
                {
                    b.HasOne("Sales.API.Models.Customer", "Customer")
                        .WithMany("OrderTickets")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("order_ticket_customer_id_fkey");

                    b.HasOne("Sales.API.Models.OrderStatus", "Status")
                        .WithMany("OrderTickets")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("order_ticket_status_id_fkey");

                    b.Navigation("Customer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Sales.API.Models.Payment", b =>
                {
                    b.HasOne("Sales.API.Models.OrderTicket", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("payment_order_id_fkey");

                    b.HasOne("Sales.API.Models.PaymentType", "PaymentType")
                        .WithMany("Payments")
                        .HasForeignKey("PaymentTypeId")
                        .HasConstraintName("payment_payment_type_id_fkey");

                    b.Navigation("Order");

                    b.Navigation("PaymentType");
                });

            modelBuilder.Entity("Sales.API.Models.Station", b =>
                {
                    b.HasOne("Sales.API.Models.StationType", "Type")
                        .WithMany("Stations")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("station_type_id_fkey");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Sales.API.Models.Customer", b =>
                {
                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("Sales.API.Models.OrderItem", b =>
                {
                    b.Navigation("CommandItems");
                });

            modelBuilder.Entity("Sales.API.Models.OrderStatus", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("OrderTickets");
                });

            modelBuilder.Entity("Sales.API.Models.OrderTicket", b =>
                {
                    b.Navigation("OrderCommands");

                    b.Navigation("OrderItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Sales.API.Models.PaymentType", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Sales.API.Models.Station", b =>
                {
                    b.Navigation("CommandItems");
                });

            modelBuilder.Entity("Sales.API.Models.StationType", b =>
                {
                    b.Navigation("Stations");
                });

            modelBuilder.Entity("Sales.API.Models.Waiter", b =>
                {
                    b.Navigation("OrderCommands");
                });
#pragma warning restore 612, 618
        }
    }
}
